added start page
GeorgeSokolovsky/internship-crm-private pull request #2
Opened 2019-02-20 12:29 UTC by stepanoves

2019-02-20 13:02 UTC, KKurchavy commented on src/app/add-article/add-article.component.ts
> +    this.addArticleService.addArticle(this.article).subscribe(() => {
По-моему надо сделать отписку

2019-02-20 13:02 UTC, KKurchavy commented on src/app/add-article/add-article.component.ts
> +  article: Article;
Наверное лучше сразу проинициализировать.
Имею ввиду ( article: Article = new Article()  );
c addArticleForm тоже самое

2019-02-20 13:02 UTC, KKurchavy commented on src/app/add-article/article.ts
> +    imgUrl: string;
Я думал мы используем название поля просто img

2019-02-20 13:02 UTC, KKurchavy commented on src/app/app.module.ts
> +    AddArticleComponent
Не очень хорошо делать всё в одном модуле

2019-02-20 13:02 UTC, KKurchavy commented on src/app/app.module.ts
> +    AppRoutingModule,
AppRoutingModule в конец списка
[Вот](https://github.com/GeorgeSokolovsky/internship-crm-public/pull/2#discussion_r258352305)

2019-02-20 13:02 UTC, KKurchavy commented on src/app/material.module.ts
> +    ]
Не уверен что это всё используется

2019-02-20 13:02 UTC, KKurchavy commented on src/app/menu/menu.component.ts
> +  ngOnInit() {
неиспользуемые методы надо убирать

2019-02-20 13:02 UTC, KKurchavy commented on src/app/add-article/add-article.component.html
> +      <input [(ngModel)]="article.title" matInput placeholder="Title" formControlName="title">
[Порядок импортов](https://github.com/GeorgeSokolovsky/internship-crm-public/pull/2#discussion_r258353878)

2019-02-20 13:03 UTC, stepanoves commented on src/app/add-article/article.ts
> +    imgUrl: string;
@KKurchavy К сожалению нет)

2019-02-20 13:06 UTC, stepanoves commented on src/app/add-article/add-article.component.ts
> +  article: Article;
@KKurchavy Я не уверен

2019-02-20 13:16 UTC, stepanoves commented on src/app/app.module.ts
> +    AddArticleComponent
@KKurchavy  Как я понимаю, ты хочешь разбить. Мне кажется это имеет смысл, если один компонент использует другой. А эти два компонента никак не связаны.

2019-02-20 13:21 UTC, GeorgeSokolovsky requested changes

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.scss
> +.add-article-container {
`:host { display: block }`

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/article.ts
> +export class Article {
А для чего этот класс в принципе?

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/app.module.ts
> +    AddArticleComponent
Да, вынеси в отдельный модуль, а тут его заимпорти

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/material.module.ts
> +    ]
Не нужно так делать лучше в каждый модуль подключать только те модули, которые используются. Иначе потом сложно будет понять, что действительно используется, а что нет.

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/menu/menu.component.ts
> +})
Поменяй на стратегию `OnPush`, если не знаешь, что это такое, почитай документацию, либо спроси у @KKurchavy он уже выслушал лекцию на эту тему

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.html
> +<form class="add-article-container" [formGroup]="addArticleForm" #formDirective="ngForm" (ngSubmit)="addArticle(formDirective)">
Давай уберем `formDirective`, мы и так сможем к  ней обратиться в методе

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.html
> +      <input [(ngModel)]="article.title" matInput placeholder="Title" formControlName="title">
Не понимаю, зачем тебе нужен `ngModel`, если у тебя есть контролы, которые ты используешь строкой ниже. Используй и тут реактивные контролы. (Если не понимаешь о чем идет речь, посмотри разницу между реактивными и шаблонными формами)

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.html
> +      <mat-hint *ngIf="addArticleForm.controls['title'].touched && addArticleForm.controls['title'].invalid">This field is required</mat-hint>
Давай в компоненте сохраним ссылки на контролы, чтобы не делать такую длинную запись

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +  providers: [AddArticleService]
`OnPush`

2019-02-20 13:21 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.service.ts
> +
Лишняя строка

2019-02-21 06:49 UTC, GeorgeSokolovsky requested changes

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +  isFieldValid(formControlName): boolean {
`isFieldInvalid` invalid же смотрим свойство

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +      this.destroy$.unsubscribe();
Нет, это неверно. У тебя не будет отписки в такой реализации. Необходимо пробросить событие в `destroy$` в `ngOnDestroy`.

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +    return this.addArticleForm.controls[formControlName].touched
вынеси получение контрола в переменную, чтобы запись не была такой длинной

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +  isFieldValid(formControlName): boolean {
Укажи тип для `formControlName`

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.module.ts
> +        FormsModule,
Для чего нужен `FormsModule`?

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.module.ts
> +        MaterialModule,
Заимпорти сюда напрямую необходимые модули из материала

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.module.ts
> +        BrowserAnimationsModule,
Мне казалось, что его одного в рутовом модуле хватит

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.module.ts
> +        HttpClientModule,
Этот по-моему тоже можно указать в рутовом и провайдеры будут доступны

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.module.ts
> +export class AddArticleModule{}
добавь пробел после имени класса

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/add-article/article.ts
> +    title: string,
оставляй `;`

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/material.module.ts
>  export class MaterialModule {}
Удаляй полностью этот модуль, он не нужен, мы будем в каждый модуль импортировать только те модули из материала, которые нужны конкретному модулю, этот же модуль только путаницу будет порождать

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/menu/menu.module.ts
> +        MaterialModule
И тут импорты напрямую с материала, а не через наш общий модуль

2019-02-21 06:49 UTC, GeorgeSokolovsky commented on src/app/menu/menu.module.ts
> +export class MenuModule{}
пробел после имени

2019-02-21 07:56 UTC, GeorgeSokolovsky requested changes

2019-02-21 07:56 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +    return this.formControls[formControlName].touched
Я не это имел в виду, formControls не нужны. Я имел в виду:
```
const {touched, invalid} = this.addArticleForm.get(formControlName);

return touched && invalid
```

2019-02-21 08:19 UTC, GeorgeSokolovsky approved these changes
Надо прикрутить prettier

2019-02-21 08:19 UTC, merged