added view articles and update articles
GeorgeSokolovsky/internship-crm-private pull request #5
Opened 2019-02-25 13:42 UTC by stepanoves

2019-02-25 14:01 UTC, GeorgeSokolovsky requested changes

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.html
> +  (ngSubmit)="forUpdate ? updateArticle() : addArticle()"
вынеси логику в компонент

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.html
> +    *ngIf="!forUpdate"
Ты ведь только текст меняешь, не нужно всю кнопку создавать через if

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
>      this.addArticleForm = this.formBuilder.group({
в кейсе обновления имя формы должно быть другое

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
>      this.addArticleForm = this.formBuilder.group({
выбери имя нейтральное к операции

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +      this.forUpdate = true;
по наличию id статьи можно определять update или create операция, флажок не очень актуален

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.component.ts
> +    this.articleForUpdateId = this.route.snapshot.params.id;
и я бы проще назвал `this.articleId`, информацию об операции тут считаю ненужной

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.service.ts
> +  updateArticle(id: string, article: AddArticle): Observable<AddArticle> {
опять путаница с именами

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/add-article/add-article.service.ts
> +  updateArticle(id: string, article: AddArticle): Observable<AddArticle> {
И по-хорошему глаголом описывается метод, интерфейс же должен описывать сущность, поэтому правильнее использовать существительное для этого описания.

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/article/article.component.scss
> +  width: 25%;
`display: block`

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/article/article.component.ts
> +  styleUrls: ['./article.component.scss'],
`OnPush`

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/articles/articles.component.ts
> +  providers: [ArticlesService],
OnPush

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/pipes/default-image.pipe.ts
> +    return value ? value : DEFAULT_IMAGE;
`value || DEFAULT_IMAGE` я это уже писал.

2019-02-25 14:01 UTC, GeorgeSokolovsky commented on src/app/pipes/default-image.pipe.ts
> +  transform(value: any): any {
принимаем `string` возвращаем `string`

2019-02-25 14:09 UTC, KKurchavy commented on src/app/add-article/add-article.service.ts
>  export class AddArticleService {
Если тут есть методы не только для добавления, а и для удаления, почему сервис тогда AddArticleService?

2019-02-25 14:10 UTC, KKurchavy commented on src/app/articles/articles.component.scss
> +  display: flex;
вроде была договоренность, что все хосты display: block;

2019-02-26 07:27 UTC, GeorgeSokolovsky requested changes

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.html
> +<form [formGroup]="articleForm" (ngSubmit)="getAction()">
почему `getAction`, тут же ничего не получается, тут производится действие. Есть 2 варианта как выбрать адекватное имя для метода, производящего действие.
1. по названию события с `on` (в нашем кейсе `onFormSubmit()`)
2. по производимому действию. (в нашем кейсе непонятно какое именно действие будет производиться, поэтому как вариант `performAction`)

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.html
> +    {{ getButtonText() }}
Плохая практика вызывать методы из шаблона, т.к. они будут вызываться при каждой перерисовке компонента. Есть 2 варианта:
1. Сохранить в поле класса и выводить поле класса.
2. Сделать через тернарный оператор внутри шаблона `hasArticleId ? 'Обновить' : 'Создать'` (это только пример, условие тернарного оператора может быть произвольным)

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +    this.articleForm = this.formBuilder.group({
вынеси создание формы из конструктора в `ngOnInit`, старайся держать в конструкторе минимум действий.

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +  addArticle() {
этот метод может быть private

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +  updateArticle() {
и этот. Правила по выбору модификатора доступа:
1. Поле / метод используются в шаблоне -> public
2. Иначе -> protected || private в зависимости от требований наследования и т.д.

Также бывают кейсы когда экземпляр компонента или директивы получается через `view | content` `child | children` и там используются методы и поля. Но кейс вполне очевидный, на мой взгляд с точки зрения модификаторов доступа.

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +    return this.articleId === undefined
можно упростить до `!this.articleId ...`

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +  ngOnInit() {
Старайся методы, который являются хуками держать выше, в идеале после конструктора

2019-02-26 07:27 UTC, GeorgeSokolovsky commented on src/app/article/article.component.scss
> +:host > * > img {
а просто для `img` класс нельзя сделать? К чему такие сложные селекторы?

2019-02-26 07:31 UTC, stepanoves commented on src/app/article-editor/article-editor.component.html
> +    {{ getButtonText() }}
@GeorgeSokolovsky У меня сначала было, как во втором пункте, но потом ты написал вынести логику и я ее вынес отовсюду)

2019-02-26 12:11 UTC, GeorgeSokolovsky requested changes

2019-02-26 12:11 UTC, GeorgeSokolovsky commented on src/app/articles/articles.component.html
> +<div style="width:100%; height:1px; clear:both;"></div>
а чего инлайновые стили заехали?

2019-02-26 12:11 UTC, GeorgeSokolovsky commented on src/app/articles/articles.component.html
> +<div style="width:100%; height:1px; clear:both;"></div>
Что-то это совсем странное

2019-02-26 14:58 UTC, GeorgeSokolovsky requested changes

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/add-category/add-category.component.ts
> +    if (!this.authService.isAuth()) this.router.navigateByUrl('/auth');
Этого в компоненте быть не должно. Это выноси в Guard для роута.

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/add-category/add-category.component.ts
> +  providers: [AddCategoryService, AuthService],
Тебе действительно нужны разные инстансы AuthService для каждого компонента?

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +    const author: string = JSON.parse(localStorage.getItem(lsTokenName)).token
Это вполне может сделать бэк. Он сможет достать из токена автора. Убираем это с фронта.

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/articles/articles.component.scss
> +  display: flex;
пусть так побудет, пока не критично

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/auth/auth.service.ts
> +    localStorage.removeItem(lsTokenName);
по хорошему на бэке должен быть logout, иначе тут бэк не знает что мы вышли

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/constants.ts
> +export const lsTokenName = 'currentUser';
Храни в оперативке, а не в LS. Т.е. через `ReplaySubject`

2019-02-26 14:58 UTC, GeorgeSokolovsky commented on src/app/utils.ts
> +export const getHttpOptions = () => {
Выставление токена делаем через Interceptor

2019-02-27 13:05 UTC, GeorgeSokolovsky requested changes

2019-02-27 13:05 UTC, GeorgeSokolovsky commented on src/app/auth/token-expired.interceptor.ts
> +        (event: HttpEvent<any>) => {},
можно и просто null передать

2019-02-27 13:05 UTC, GeorgeSokolovsky commented on src/app/sign-up/sign-up.component.ts
> +  providers: [AuthService],
Точно нужно здесь еще раз провайдить что-то? OnPush?

2019-02-27 13:05 UTC, GeorgeSokolovsky commented on src/app/sign-up/sign-up.component.ts
> +    if (this.authService.isAuth()) this.router.navigateByUrl('/article');
А как же guard?

2019-02-27 13:05 UTC, GeorgeSokolovsky commented on src/app/sign-up/sign-up.service.ts
> +export class SignUpService {}
Не нужен?

2019-02-27 14:48 UTC, GeorgeSokolovsky requested changes

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/app-routing.module.ts
> +  providers: [],
лишний код

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/article-editor/article-editor.component.ts
> +    if (this.articleId !== undefined) {
Отдели if от строки выше (для красоты). Запись можно упростить до `if (this.articleId) ...`

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/article/article.component.scss
> +  flex-basis: 21%;
Лучше так не делать. Таким образом ты лишаешь свой компонент возможности встраиваться куда угодно. Перенеси эти стили в место, где этот компонент используется.

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/auth/auth.component.ts
> +    this.destroy$.unsubscribe();
`this.destroy$.next()`?

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/auth/auth.component.ts
> +    const { touched, invalid } = this.authForm.get(formControlName);
Давай вынесем эту функцию в утилиты. Напомни покажу как.

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/constants.ts
> +export const lsTokenName = 'currentUser';
забудем

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/menu/menu.component.ts
> +  providers: [AuthService],
Почему опять в компоненте?

2019-02-27 14:48 UTC, GeorgeSokolovsky commented on src/app/sign-up/sign-up.component.ts
> +    this.destroy$.unsubscribe();
next же

2019-02-27 14:54 UTC, stepanoves commented on src/app/menu/menu.component.ts
> +  providers: [AuthService],
@GeorgeSokolovsky потому что он тут используется)

2019-02-28 07:56 UTC, KKurchavy commented on src/app/add-category/add-category.component.ts
> +  isFieldInvalid;
где тип?

2019-02-28 08:12 UTC, GeorgeSokolovsky approved these changes

2019-02-28 08:12 UTC, merged